using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Trinity.Encore.Framework.Game.Protocol
{
    /// <summary>
    /// A list of packet opcodes gleaned from client version 4.0.1.13205.
    /// </summary>
    enum Opcodes : uint
    {
        CMSG_CHAR_CUSTOMIZE = 0x250,
        SMSG_CHAR_DELETE = 0x278,
        CMSG_CHAR_ENUM = 0x3F8,
        SMSG_ADDON_INFO = 0xAF9,
        SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED = 0xB54,
        CMSG_PING = 0x1001,
        SMSG_COMPLAIN_RESULT = 0x2295,
        SMSG_SET_PROFICIENCY = 0x22D4,
        SMSG_REPORT_PVP_AFK_RESULT = 0x239D,
        SMSG_CHAT_RESTRICTED = 0x23BC,
        SMSG_CHAT_PLAYER_AMBIGUOUS = 0x2A94,
        MSG_TALENT_WIPE_CONFIRM = 0x2A95,
        CMSG_CHAR_CREATE = 0x2BF0,
        CMSG_AUTH_SESSION = 0x3000,
        SMSG_REALM_SPLIT = 0x4270,
        SMSG_CHAR_ENUM = 0x429C,
        SMSG_PET_NAME_INVALID = 0x42D9,
        SMSG_FISH_ESCAPED = 0x431D,
        SMSG_MEETINGSTONE_MEMBER_ADDED = 0x43FD,
        SMSG_NEW_WORLD = 0x4A5D,
        SMSG_TRIGGER_CINEMATIC = 0x6310,
        SMSG_LOGOUT_RESPONSE = 0x63BC,
        SMSG_GMTICKET_SYSTEMSTATUS = 0x6A51,
        CMSG_READY_FOR_ACCOUNT_DATA_TIMES = 0x6A99,
        SMSG_PLAYERBOUND = 0x827D,
        SMSG_ACCOUNT_DATA_TIMES = 0x82B5,
        SMSG_LOGOUT_COMPLETE = 0x8311,
        SMSG_ITEM_PUSH_RESULT = 0x835D,
        SMSG_CREATURE_QUERY_RESPONSE = 0x83B8,
        SMSG_AUTH_CHALLENGE = 0x8500,
        MSG_RANDOM_ROLL = 0x8A5D,
        CMSG_CHAR_DELETE = 0x8A78,
        SMSG_TOGGLE_XP_GAIN = 0x8AB8,
        SMSG_EXPLORATION_EXPERIENCE = 0x8B58,
        SMSG_PETGODMODE = 0x8B99,
        SMSG_UPDATE_OBJECT = 0x8BF0,
        SMSG_BINDPOINTUPDATE = 0xA255,
        SMSG_NEW_TAXI_PATH = 0xA259,
        SMSG_CHAR_RENAME = 0xA33C,
        SMSG_LOGOUT_CANCEL_ACK = 0xA395,
        CMSG_CHAR_RENAME = 0xAB38,
        CMSG_REALM_SPLIT = 0xAB58,
        SMSG_CHAR_CREATE = 0xC211,
        SMSG_PLAYERBINDERROR = 0xC3FC,
        SMSG_FISH_NOT_HOOKED = 0xCAB5,
        SMSG_LEVELUP_INFO = 0xCB15,
        SMSG_CHARACTER_LOGIN_FAILED = 0xCBD9,
        SMSG_CLIENTCACHE_VERSION = 0xE2B8,
        SMSG_CHAT_WRONG_FACTION = 0xE2D4,
        SMSG_CALENDAR_EVENT_INVITE = 0xE2FC,
        SMSG_AUTH_RESPONSE = 0xEB58,
        SMSG_CHAR_CUSTOMIZE = 0xE2B5
    }
}
